# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto_Clockin_GitHub_Action

on:
    workflow_dispatch:
    schedule:
    - cron: '30 17 * * *'
      # 👆在上面那行修改打卡时间
      # 1:30 everyday in UTC+8, 17:30 everyday in UTC+0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip3 install torch==1.10.2+cpu torchvision==0.11.3+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html

    - name: Start Clocking in
      env:
          username:   ${{ secrets.USERNAME }}
          password:   ${{ secrets.PASSWORD }}
          province:   ${{ secrets.PROVINCE }}
          city:       ${{ secrets.CITY }}
          county:     ${{ secrets.COUNTY }}
      run: |
        python clock_in.py --username=$username --password=$password --province=$province --city=$city --county=$county
